name: Deploy to PyPI
on:
  push:
    branches:
      - master
jobs:
  DeployToPyPI:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set the Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0
      - name: Install twine dependency
        run: pip install twine==4.0.2
      - name: Install setuptools dependency
        run: pip install setuptools==69.0.3
      - name: Install wheel dependency
        run: pip install wheel==0.42.0
      - name: Execute the Python sdist package build
        run: python setup.py sdist
      - name: Execute the Python bdist_wheel package build
        run: python setup.py bdist_wheel
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_TOKEN }}